<template>
  <div class="loadingio-spinner-pulse-am6cj1r8p8">
    <div class="ldio-t4mlfjk7hl">
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style type="text/css">
@keyframes ldio-t4mlfjk7hl-1 {
  0% {
    top: 18px;
    height: 64px;
  }
  50% {
    top: 30px;
    height: 40px;
  }
  100% {
    top: 30px;
    height: 40px;
  }
}
@keyframes ldio-t4mlfjk7hl-2 {
  0% {
    top: 20.999999999999996px;
    height: 58.00000000000001px;
  }
  50% {
    top: 30px;
    height: 40px;
  }
  100% {
    top: 30px;
    height: 40px;
  }
}
@keyframes ldio-t4mlfjk7hl-3 {
  0% {
    top: 24px;
    height: 52px;
  }
  50% {
    top: 30px;
    height: 40px;
  }
  100% {
    top: 30px;
    height: 40px;
  }
}
.ldio-t4mlfjk7hl div {
  position: absolute;
  width: 15px;
}
.ldio-t4mlfjk7hl div:nth-child(1) {
  left: 17.5px;
  background: #0a7142;
  animation: ldio-t4mlfjk7hl-1 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.2s;
}
.ldio-t4mlfjk7hl div:nth-child(2) {
  left: 42.5px;
  background: #13a365;
  animation: ldio-t4mlfjk7hl-2 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.1s;
}
.ldio-t4mlfjk7hl div:nth-child(3) {
  left: 67.5px;
  background: #0a7142;
  animation: ldio-t4mlfjk7hl-3 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: undefineds;
}

.loadingio-spinner-pulse-am6cj1r8p8 {
  width: 45px;
  height: 45px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-t4mlfjk7hl {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.45);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-t4mlfjk7hl div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
